using System.Runtime.InteropServices;

namespace ConsoleApp1.SendInput.Types
{
    // https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-hardwareinput
    // only interesting for hardware other than mouse and keyboard
    [StructLayout(LayoutKind.Sequential)]
    public struct HardwareInput
    {
        public uint uMsg;      //  message generated by the input hardware
        public ushort wParamL; // low-order word of the lParam parameter for uMsg
        public ushort wParamH; // high-order word of the lParam parameter for uMsg
    }
}